# -*- coding: utf-8 -*-
"""Netflix_Data_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FJns3Y9FlZ-s0kfqYCf-hYkSVy6XYV9r

# Importing Libraries
"""

import pandas as pd
import numpy as np
import plotly.express as px 
from textblob import TextBlob 
import seaborn as sns
import matplotlib.pyplot as plt

"""# Reading Dataset"""

df = pd.read_csv('/content/netflix_titles.csv.zip')
df.head()

"""## Null Values Handling"""

df.shape

df.isnull().sum()

"""### As Rajiv Cilaka is an Indian Directors who helmed the project of directing 'Chota Bheem', I have filled his country which were null values

By this way also we can fill null values for some section of the data based on condition.
"""

df.loc[df['director']=='Rajiv Chilaka', 'country'] = 'India'

"""## Droping rest of null values as we have abandance of data-points in out dataset."""

df.dropna(inplace=True)

df.shape

df.columns

"""# Data analysis of netflix data
------------------------------************-------------------------------------

# Top-10 Content Ratings on Netflix
"""

z = df.groupby(['rating']).size().reset_index(name='counts').sort_values('counts',ascending=False).head(10)
pieChart = px.pie(z, values='counts', names='rating', 
                  title='Distribution of Top-10 Content Ratings on Netflix',
                  color_discrete_sequence=px.colors.qualitative.Set3)
pieChart.show()

"""# Top 10 Directors on Netflix"""

ad = df.groupby(['director']).agg(count=('show_id','count')).sort_values('count', ascending=False).head(10).reset_index()
fig1=px.bar(ad,x='count',y='director',title='Top 10 Directors on Netflix')
fig1.show()

"""# Top-10 Actors with most occurance on Netflix"""

lst=df['cast'].str.split(',',expand=True).stack()
lst=lst.to_frame()
lst.columns=['cast']
lst=lst.groupby(['cast']).size().reset_index(name='occurance')
lst=lst.sort_values('occurance', ascending=False)
fig2=px.bar(lst.head(10),x='cast',y='occurance', title='Top 10 Actors with most occurance on Netflix')
fig2.show()

"""# Trend of content produced over the years on Netflix"""

df1 = df[['type','release_year']]
df1=df1.groupby(['type','release_year']).size().reset_index(name='count')
df1=df1[df1['release_year']>=2010]
fig3 = px.line(df1, x="release_year", y="count", color='type',title='Trend of content produced over the years on Netflix')
fig3.show()

# df1=df.groupby(['type','release_year']).agg(d=('release_year','count'))
# df1=df1.reset_index()
# df1=df1[df1['release_year']>=2010]
# sns.lineplot(x='release_year', y='d', data=df1, hue='type')

"""## We can know the sentiments of a sentence by using below method.
## Now we have description columns and we will try to find the sentiment of that movie and also see how movies sentiments are changing over the years
"""

z = 'my name is rahul singh. I am going to become a data analyst'
testimonial=TextBlob(z)
p=testimonial.sentiment.polarity

if p==0:
    sent='Neutral'
elif p>0:
    sent='Positive'
else:
    sent='Negative'

print(sent)

"""# Sentiment of content on Netflix"""

dfx=df[['release_year','description']]
dfx=dfx.rename(columns={'release_year':'Release Year'})
for index,row in dfx.iterrows():
    z=row['description']
    testimonial=TextBlob(z)
    p=testimonial.sentiment.polarity
    if p==0:
        sent='Neutral'
    elif p>0:
        sent='Positive'
    else:
        sent='Negative'
    dfx.loc[[index],'Sentiment']=sent


dfx=dfx.groupby(['Release Year','Sentiment']).size().reset_index(name='Total Content')

dfx=dfx[dfx['Release Year']>=2010]
fig4 = px.bar(dfx, x="Release Year", y="Total Content", color="Sentiment", title="Sentiment of content on Netflix")
fig4.show()

df_year = df.groupby(['release_year']).agg({'title':'nunique'}).reset_index()
plt.figure(figsize = (12,6))
sns.lineplot(x='release_year',y = 'title',data=df_year,color = 'blue')
plt.xticks(rotation = 60)
plt.title('Total content added throughout the year')

plt.figure(figsize = (12,5))
sns.countplot(x = 'release_year',order = df['release_year'].value_counts().index[0:10],data = df,palette = 'mako')
plt.title('Content release over the Years on Netflix')

"""Rahul singh ( masai school ) 29_march_2023 Netfilx data Analysis Project"""

